services:
  serverkit-dev:
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev

  serverkit-prod:
    build:
      context: .
      target: production
      args:
        - VITE_ANALYTICS_SCRIPT_URL=${VITE_ANALYTICS_SCRIPT_URL:-}
        - VITE_ANALYTICS_WEBSITE_ID=${VITE_ANALYTICS_WEBSITE_ID:-}
      ports:
        - "3000:3000"
    profiles:
      - prod
